language: ruby
cache: bundler
rvm:
 - 2.5.0
branches:
  only:
  - gh-pages
script: 
- bundle exec jekyll build
sudo: false
deploy:
  provider: pages
  local-dir: ./_site
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
notifications:
  email:
    recipients:
      - smaroukis@gmail.com
    on_success: always
    on_failure: always
