language: python # we will use the ruby of the docker container
os: linux
dist: bionic
before_install:
  - docker pull jekyll/jekyll:3.8
branches:
  only:
  - master-source
script: 
  - docker run --rm -it -v="$PWD:/srv/jekyll" jekyll/jekyll:3.8 jekyll build
deploy:
  provider: pages
  local_dir: _site/
  skip_cleanup: true
  target-branch: master
  token: $GITHUB_TOKEN
  strategy: git
  keep_history: true
  on:
    branch: master-source
notifications:
  email:
    recipients:
      - smaroukis@gmail.com
    on_success: always
    on_failure: always
