language: python # since we will use the ruby of the docker image 
before_install:
  - docker pull jekyll/jekyll:3.8
branches:
  only:
  - gh-pages
script: 
  - docker run --rm -it -v="$PWD:/srv/jekyll" jekyll/jekyll:3.8 "jekyll build"
sudo: false
deploy:
  provider: pages
  local-dir: ./_site
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
notifications:
  email:
    recipients:
      - smaroukis@gmail.com
    on_success: always
    on_failure: always
