#
###################################
# Site wide configuration & SEO
####################################
#
title: Spencer's Power Blog
tagline: A blog about power systems and electrical engineering
email: smaroukis@gmail.com
description: Electrical engineer. Previously University of Michigan and Pacific Gas & Electric. 
url: https://smaroukis.github.io # the base hostname & protocol for your site
keywords: ["Power Systems", "Energy", "Clean Tech"]
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/blog-default-card.png

#
###################################
# Jekyll configuration
####################################
#
timezone:          Los Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /blog/:title
theme: leonids
plugins:
  - jekyll-seo-tag
exclude: [vendor, docker-compose.yml, Gemfile]
include: [.nojekyll, .placeholder_for_travis]

sass:
    sass_dir: ./_sass

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Spencer
  avatar: assets/img/avatar.jpg
  job: "Power Systems Engineer"
  bio: "Electron traffic control"
  email: smaroukis@gmail.com 
  disqus-shortname: 
  twitter: that_marouk_ish #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  github: smaroukis #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: spencermaroukis #username
  instagram: #username
