#
###################################
# Site wide configuration
####################################
#
title: Spencer
email: smaroukis@gmail.com
description: Electrical engineer @ Pacific Gas & Electric operating the distribution grid.
url: https://smaroukis.github.io # the base hostname & protocol for your site
keywords: ["Power Systems", "Energy", "Clean Tech"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Los Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title
theme: leonids

sass:
    sass_dir: ./_sass

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Spencer
  avatar: headshot.jpg
  job: "Power Systems Engineer"
  bio: "Electron traffic controller by week, rock climber by weekend."
  email: smaroukis@gmail.com 
  disqus-shortname: 
  twitter: that_marouk_ish #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: smaroukis #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: spencermaroukis #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
