# for local development only; for deployment use JEKYLL_ENV=production and --config _config.yml
# usage: `docker compose up`
version: '3.7'
services:
  site:
    environment:
      - JEKYLL_ENV=local # can be anything other than 'production', to override url
    command: jekyll serve --drafts --incremental --force_polling --watch --config _config.yml,_config.docker.yml # needed for windows see https://tonyho.net/jekyll-docker-windows-and-0-0-0-0/ 
    image: jekyll/jekyll:3.8
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000 