# for local development only; for deployment use JEKYLL_ENV=production and --config _config.yml
# usage: `docker compose up`
version: '3.7'
services:
  site:
    command: jekyll serve --env JEKYLL_ENV=docker --incremental --drafts --config _config.yml,_config.docker.yml # needed for windows see https://tonyho.net/jekyll-docker-windows-and-0-0-0-0/ 
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000